@startuml

package Datasource {
class AttendanceRecordRepositoryCSV {
-attendanceRecords : AttendanceRecords 
+load()
+save()
}
}

package Domain {
class Year {
-year:int
+getYear()
}
class Month {
-month:int
+getMonth()
}
class Day {
-day:int
+getDay()
}
class WorkingDate {
-year : Year
-month : Month
-day : Day
getYearMonth()
getDate()
}


WorkingDate *-down- Year
WorkingDate *-down- Month
WorkingDate *-down- Day

class YearMonth {
-year : Year
-month : Month
}

YearMonth *-down= Year
YearMonth *-down- Month

class EntryTime {
  -hour : Hour
  -minute : Minute
  getMinutes()
}

class WorkingDuration {
startTime : EntryTime
endTime : EntryTime
}

WorkingDuration *-down- EntryTime  : have 2 

class RegularTimeRule {
-startTime : EntryTime 
-endTime : EntryTime 
}

Enum BreakTimeRules {
LUNCH_BREAK_TIME,
EVENING_BREAK_TIME,
LATE_NIGHT_BREAK_TIME
}

class BreakTimeRule {
static breakTimeStart : EntryTime　:休憩開始
static breakTimeEnd   : EntryTime　:休憩終了
}

BreakTimeRules *-down- BreakTimeRule 


class OverTimeRule {
-finalCutTime : entryTime  
}

class AttendanceRecords {
-List<AttendanceRecord>
}

class AttendanceRecord {
-workingDate : WorkingDate
-startTime : EntryTime
-endTime : EntryTime
}

AttendanceRecords *-down- AttendanceRecord 

interface AttendanceRecordRepository {
-record: AttendanceRecords
+insert()
+load()
+save()
}

class AttendanceSummary {
+toString()
+formatString()
-fired : boolean 
-regularWorkingHours : Duration
-overTimeWokringHours : Duration
}

}
package API {
class CommandLineParserAPI
}
package Service
{
class AttendanceRecordUpdateService {
executeSerice(AttendanceRecord)
}
class AttendanceRecordSummaryService
{
executeService(YearMonth)
}

AttendanceRecordUpdateService o--  AttendanceRecordRepository 
AttendanceRecordUpdateService <.. OverTimeRule
AttendanceRecordSummaryService o-- AttendanceRecordRepository
AttendanceRecordSummaryService <.. BreakTimeRules
AttendanceRecordSummaryService <.. RegularTimeRule
AttendanceRecordSummaryService <.. AttendanceSummary 
AttendanceRecordSummaryService <.. YearMonth 

CommandLineParserAPI --> AttendanceRecordUpdateService : AttendanceRecord
CommandLineParserAPI --> AttendanceRecordSummaryService : YearMonth

AttendanceRecord <.. WorkingDate
AttendanceRecord <.. WorkingDuration
AttendanceRecords <.. AttendanceRecord
AttendanceRecordRepositoryCSV  <.. AttendanceRecords

AttendanceRecordRepository o.. AttendanceRecordRepositoryCSV


@enduml
