@startuml
class com.naosim.dddwork.domain.DailyWorkData {
- WorkDate workDate
- Total1DayWorkTimes totalWorkTimes
~ <<Create>> DailyWorkData(WorkDate,TimeMoment,TimeMoment)
~ WorkDate getWorkDate()
}


class com.naosim.dddwork.domain.WorkTimeMoments {
- TimeMoment startWorkTime
- TimeMoment endWorkTime
- PrescribedWorkHours prescribedWorkHours
~ <<Create>> WorkTimeMoments(TimeMoment,TimeMoment)
~ TimeMoment getStartWorkTime()
~ TimeMoment getEndWorkTime()
}


class com.naosim.dddwork.domain.DailyWorkDataList {
- List<DailyWorkData> workDataList
- int workingDays
~ <<Create>> DailyWorkDataList()
~ void UpdateWorkingDays()
~ boolean ValidateWorkingDays()
}


class com.naosim.dddwork.domain.WorkDate {
- LocalDate yearMonth
~ <<Create>> WorkDate(int,int,int)
~ <<Create>> WorkDate(WorkDate)
~ LocalDate getYearMonth()
}


class com.naosim.dddwork.domain.Total1MonthTimeMoments {
- long total1MonthTimeMoments
~ <<Create>> Total1MonthTimeMoments()
}


class com.naosim.dddwork.Main {
+ {static} void main(String[])
}

class com.naosim.dddwork.domain.MinutesDifference {
- long timeDifference
~ <<Create>> MinutesDifference(TimeMoment,TimeMoment)
~ <<Create>> MinutesDifference(MinutesDifference)
~ boolean ValidateMinutesDifference()
~ void SubtractMinutesDifference(long)
~ long GetMinutesDifference()
}


class com.naosim.dddwork.domain.PrescribedWorkHours {
- TimeMoment PRESCRIBE_START_WORK_TIME
- TimeMoment PRESCRIBE_END_WORK_TIME
- MinutesDifference timeDifference
~ <<Create>> PrescribedWorkHours()
~ TimeMoment GetPrescribeStartWorkTime()
}


class com.naosim.dddwork.domain.BreakTimeMoments {
- TimeMoment startBreakTime
- TimeMoment endBreakTime
~ <<Create>> BreakTimeMoments(TimeMoment,TimeMoment)
~ <<Create>> BreakTimeMoments(BreakTimeMoments)
~ TimeMoment getStartBreakTime()
~ TimeMoment getEndBreakTime()
~ MinutesDifference getBreakTimeDifference()
}


class com.naosim.dddwork.domain.TimeMoment {
~ LocalTime moment
~ <<Create>> TimeMoment(int,int)
~ <<Create>> TimeMoment(TimeMoment)
}


class com.naosim.dddwork.domain.HoursDifference {
- long hourDifference
~ <<Create>> HoursDifference(TimeMoment,TimeMoment)
+ boolean CheckHourDifference()
}


class com.naosim.dddwork.domain.Total1DayWorkTimes {
- MinutesDifference total1DayWorkTimes
- BreakTimeMomentsList BREAK_TIME_MOMENTS_LIST
~ <<Create>> Total1DayWorkTimes(WorkTimeMoments)
}


class com.naosim.dddwork.domain.BreakTimeMomentsList {
- List<BreakTimeMoments> breakTimeMomentsList
~ <<Create>> BreakTimeMomentsList()
~ List<BreakTimeMoments> getBreakTimeMomentsList()
}


@enduml