@startuml
class com.naosim.dddwork.domain.daily_work.BreakTimeMomentsList {
- List<BreakTimeMoments> breakTimeMomentsList
~ List<BreakTimeMoments> getBreakTimeMomentsList()
}


class com.naosim.dddwork.domain.daily_work.BreakTimeMoments {
- TimeMoment startBreakTime
- TimeMoment endBreakTime
~ TimeMoment getStartBreakTime()
~ TimeMoment getEndBreakTime()
~ TimeMomentsDifference getBreakTimeDifference()
}


class com.naosim.dddwork.domain.Total1MonthOverworkTimes {
- Total1MonthTimeMoments totalOverworkTimes
~ Total1MonthTimeMoments getTotalOverworkTimes()
}


class com.naosim.dddwork.domain.Total1MonthWorkTimes {
- Total1MonthTimeMoments total1MonthWorkTimes
~ Total1MonthTimeMoments getTotal1MonthWorkTimes()
}


class com.naosim.dddwork.domain.daily_work.DailyWorkData {
- WorkDate workDate
- Total1DayWorkTimes totalWorkTimes
+ WorkDate getWorkDate()
+ Total1DayWorkTimes getTotalWorkTimes()
}


class com.naosim.dddwork.domain.DailyWorkDataList {
- List<DailyWorkData> workDataList
- int workingDays
~ void updateWorkingDays()
~ boolean validateWorkingDays()
~ List<DailyWorkData> getDailyWorkDataList()
~ int getWorkingDays()
}


interface com.naosim.dddwork.domain.InputWorkDataRepository {
+ {static} DailyWorkDataList workDataList
~ void writeDailyWorkData()
}


class com.naosim.dddwork.domain.daily_work.HoursDifference {
- long hourDifference
+ boolean checkHourDifference()
}


class com.naosim.dddwork.domain.daily_work.DateMoments {
- LocalDate date
+ LocalDate getDate()
}


class com.naosim.dddwork.domain.Total1MonthTimeMoments {
- long total1MonthTimeMoments
~ void AddTimes(long)
~ long GetTotalTimes()
}


class com.naosim.dddwork.domain.daily_work.TimeMoment {
~ LocalTime moment
}

class com.naosim.dddwork.domain.Total1MonthNormalWorkTimes {
- Total1MonthTimeMoments totalNormalWorkTimes
}

class com.naosim.dddwork.domain.daily_work.ScheduledWorkTimes {
- TimeMoment SCHEDULED_START_TIME
- TimeMoment SCHEDULED_END_TIME
- TimeMomentsDifference scheduledWorkTimes
+ TimeMomentsDifference getScheduledWorkTimes()
~ TimeMoment getScheduledStartTime()
}


class com.naosim.dddwork.Main {
+ {static} void main(String[])
}

class com.naosim.dddwork.domain.daily_work.WorkTimeMoments {
- TimeMoment startWorkTime
- TimeMoment endWorkTime
- ScheduledWorkTimes scheduledWorkHours
~ TimeMoment getStartWorkTime()
~ TimeMoment getEndWorkTime()
}


class com.naosim.dddwork.domain.daily_work.Total1DayWorkTimes {
- TimeMomentsDifference total1DayWorkTimes
- BreakTimeMomentsList BREAK_TIME_MOMENTS_LIST
+ TimeMomentsDifference getTotal1DayWorkTimes()
}


class com.naosim.dddwork.domain.daily_work.TimeMomentsDifference {
- Duration timeDifference
~ boolean validateTimeMomentsDifference()
~ void subtractTimeMomentsDifference(long)
+ Duration getTimeMomentsDifference()
}


interface com.naosim.dddwork.domain.FetchWorkDataRepository {
+ {static} DailyWorkDataList workDataList
~ DailyWorkDataList fetchDailyWorkData()
}


class com.naosim.dddwork.domain.daily_work.WorkDate {
- DateMoments workDate
+ DateMoments getDateMoments()
}


@enduml