@startuml
'コメントアウト

class Api {
  main()
  inputApi()
  totalApi()
}


class  Service {
  inputService()
  totalService()
}

class Domain {
  inputData()
  outputData()
}

interface IRepository {
  writeData()
  readData()
}


class RepositoryDb implements IRepository {
  writeData()
  readData()
} 

class ArgsAndCheckVO {
  checkArgsLength()
  getMethodtype()
  inputCheckArgsLength()
  totalCheckArgsLength()
  getDate()
  getStart()
  getEnd()
}

enum MethodType {
  input
  total
}

class DateVO {
  date
  getDate()
}

class StartTimeVO {
  start
  startHour
  startMinute
  getStart()
  getStartTotalMinute()
}


class EndTimeVO {
  end
  endHour
  endMinute
  getEnd()
  getEndHour()
  getEndMinute()
  getEndTotalMinute()
}

class WorkTimeVO {
  workTime
  overWorkTime
  tmpBreakTime
  getWorkTime()
  getOverWorTime()
}

class NowVO {
  now
  getNow()
}


Api .down.> Service
Service .down.> Domain
Domain .down.> IRepository

Api .right.> ArgsAndCheckVO
ArgsAndCheckVO .right.> MethodType

Domain .right.> WorkTimeVO
Domain .right.> DateVO
Domain .right.> StartTimeVO
Domain .right.> EndTimeVO

RepositoryDb .right.> NowVO


@enduml
