@startuml
'コメントアウト

class Api {
  inputApi()
  totalApi()
}


class  Service {
  inputData()
  outputData()
}

class Domain {

}

interface IRepository {

}


class RepositoryDb implements IRepository {

} 

class ArgsVO {
  checkArgsLength()
  getMethodtype()
  inputCheckArgsLength()
  totalCheckArgsLength()
}

enum MethodType {
  input
  total
}



class EndTimeVO {

}



Api .down.> Service
Service ..> Domain
Domain ..> IRepository
Api .right.> ArgsVO
ArgsVO .right.> MethodType
Domain ..> WorkTimeVO
Domain ..> StartTimeVO
Domain ..> EndTimeVO


@enduml
