@startuml kintaiD
package ドメインモデル{
    package 就業日勤務実績{
        class 勤務実績{
            勤務日
            開始時刻
            終了時刻
            残業時間
            勤務時間
        }
        class 残業{
            残業時間
        }
        class 勤務時間{
            勤務時間
        }

    }
    package 勤務入力{
        class 勤務記録{
            勤務日
            開始時刻
            終了時刻
        }
        class 勤務日{
         }
        class 業務開始時刻{
         }
        class 業務終了時刻{
        }
    }
    package 就業関連規則{
        class 就業規則{
            始業時刻
            終業時刻
            休憩時刻

            休憩時間計算()
        }


        class 休憩{
            休憩開始時刻
            休憩終了時刻
        }
        class 始業規定時刻{
        }
        class 終業規定時刻{
        }
    }


    package 選択一月合計勤務残業時間 {
        class 月合計勤務時間{
            月合計勤務時間
            月合計残業時間
            月合計勤務残業計算(月集計就業日合計記録リスト)
        }
        class 月合計勤務{
        }
        class 月合計残業{
        }
    }
    勤務実績 ..> 勤務時間
    勤務実績 ..> 残業
    勤務実績 ..> 就業規則
    勤務実績 ..> 勤務記録

    就業規則 ..> 休憩
    就業規則 ..> 始業規定時刻
    就業規則 ..> 終業規定時刻
    
    勤務記録 ..> 勤務日
    勤務記録 ..> 業務開始時刻
    勤務記録 ..> 業務終了時刻

    月合計勤務時間 ..> 勤務実績
    月合計勤務時間 ..> 月合計勤務
    月合計勤務時間 ..> 月合計残業
}
package サービス層{
    class 勤務記録入力サービス{

    }
    interface 就業日合計記録リポジトリ{

    }
    class 月合計勤務時間サービス{
    }

    勤務記録入力サービス ..> 勤務実績
    勤務記録入力サービス ..> 就業日合計記録リポジトリ
    勤務記録入力サービス ..> 勤務記録
    勤務記録入力サービス ..> 就業規則
    就業日合計記録リポジトリ ..> 勤務実績
    月合計勤務時間サービス ..> 就業日合計記録リポジトリ
    月合計勤務時間サービス ..> 月合計勤務時間
    月合計勤務時間サービス ..> 勤務実績

}
@enduml