@startuml kintaiD
package ドメインモデル{
    class 勤務記録{
        勤務日
        開始時刻
        終了時刻
    }
    class 就業規則{
        始業時刻
        終業時刻
        休憩時刻
    }
    class 休憩残業算出{
        就業時間
        休憩時間
        残業時間

    }
    class 休憩{
        休憩時間
    }
    class 残業{
        残業時間
    }
    class 就業時間{
        就業時間
    }
    class 勤務時間{
        勤務時間
    }
    class 就業日合計記録{
        勤務日
        開始時刻
        終了時刻
        残業時間
        勤務時間
    }
    class 月合計勤務時間{
        月合計勤務時間
        月合計残業時間
    }
    休憩残業算出 ..> 就業規則
    休憩残業算出 ..>勤務記録
    休憩 ..>休憩残業算出
    残業 ..>休憩残業算出

    就業時間 ...> 休憩残業算出
    勤務時間 ..> 休憩
    勤務時間 ..> 就業時間
    就業日合計記録 ..> 勤務時間
    就業日合計記録 ..> 勤務記録
    就業日合計記録 ..> 残業  
    月合計勤務時間 ..> 就業日合計記録
}
@enduml