@startuml kintaiD
package ドメインモデル{
    class 勤務記録{
        勤務日
        開始時刻
        終了時刻
    }
    class 就業規則{
        始業時刻
        終業時刻
        休憩時刻

        休憩時間計算()
    }
    class 勤務日{
    }
    class 業務開始時刻{
    }
    class 業務終了時刻{
    }

    class 休憩{
        休憩開始時刻
        休憩終了時刻
    }
    class 残業{
        残業時間
    }
    
    class 勤務時間{
        勤務時間
    }
    class 就業日合計記録{
        勤務日
        開始時刻
        終了時刻
        残業時間
        勤務時間
    }
    class 月合計勤務時間{
        月合計勤務時間
        月合計残業時間
    }
    class 月合計勤務{
    }
    class 月合計残業{
    }
    就業日合計記録 ..> 勤務時間
    就業日合計記録 ..> 残業
    就業日合計記録 ..> 就業規則
    就業日合計記録 ..> 勤務記録

    就業規則 ..> 休憩
    就業規則 ..> 勤務日
    就業規則 ..> 業務開始時刻
    就業規則 ..> 業務終了時刻
    
    勤務記録 ..> 勤務日
    勤務記録 ..> 業務開始時刻
    勤務記録 ..> 業務終了時刻

    月合計勤務時間 ..> 就業日合計記録
    月合計勤務時間 ..> 月合計勤務
    月合計勤務時間 ..> 月合計残業
}
package サービス層{
    class 勤務記録入力サービス{

    }
    interface 就業日合計記録リポジトリ{

    }
    勤務記録入力サービス ..> 就業日合計記録
    勤務記録入力サービス ..> 就業日合計記録リポジトリ
    勤務記録入力サービス ..> 勤務記録
    就業日合計記録リポジトリ..> 就業日合計記録
    勤務記録入力サービス ..> 就業規則
    
}
@enduml