@startuml


package API{

    package コントローラ{
        class 入力コントローラ{
         - {field} 入力サービス
         + {method} void execute(String[])
        }
        class 集計コントローラ{
         - {field} 月間集計サービス
         + {method} void execute(String[])
         - {method} void consoleOut(月間サマリ)
         - {method} String outputString(月間サマリ)
        }

        top to bottom direction
        入力コントローラ -[hidden]-集計コントローラ
    }


    class バリデータ{
     + {method} isValidArgs(String[])
     - {method} isValidMethodType(String)
    }

}

package サービス{

    class 入力サービス{
     - {field} 勤怠リポジトリ
     - {field} レコーダー
     + {method}void persist(対象日付, 開始時刻, 終了時刻)
    }

    class 月間集計サービス{
     - {field} 勤怠リポジトリ
     + {method}List<勤怠レコード> getMonthlySummary(対象年月)
    }

    top to bottom direction
    入力サービス -[hidden]-月間集計サービス
}


package ドメイン{

    package リポジトリ{
        interface 勤怠リポジトリ{
           void write(勤怠レコード)
           List<勤怠レコード> read(対象年月)
        }
    }

    package 勤怠レコード{

        class 勤怠レコード{
          {field} 対象日付
          {field} タイムカード
          {field} 労働時間
          {field} 登録時刻

          + {method} int getActualWorkingMinutesValue()
          + {method} int getOvertimeValue()
        }

        勤怠レコード -down-> 対象日付
        勤怠レコード -down-> タイムカード
        勤怠レコード -down-> 労働時間
        勤怠レコード -down-> 登録時刻

        class レコーダー{
          {field} 休憩時間リスト
          {field} 定時間
          {field} 登録時刻

          + {method} 勤怠レコード record(対象日付,開始時刻,終了時刻)
        }

        入力サービス -down-> レコーダー

        package 対象日付{
            class 対象日付 {
            {field} LocalDate
            + {method}String toString(DateTimeFormatter)
            }
        }

        package タイムカード {

            class タイムカード {
            {field} 開始時刻
            {field} 終了時刻
             +{method}int getOperatingMinutes()
             -{method}void valid(開始時刻,終了時刻)
            }

            class 開始時刻 {
            {field} LocalTime
             +{method}String toString()
             +{method}int getMinutes()
            }

            class 終了時刻 {
             {field} LocalTime
             +{method}String toString()
             +{method}int getMinutes()
            }

            タイムカード -down-> 開始時刻
            タイムカード -down-> 終了時刻

        }


        package 労働時間{
            package 拘束と実働時間{
                class 拘束時間{
                {field} int
                {static} 拘束時間 create(タイムカード)
                }

                class 休憩時間{
                {field} LocalTime start
                {field} LocalTime end
                }

                class 休憩時間リスト{
                {field} List<休憩時間> breakTimes
                }

                休憩時間リスト o-- 休憩時間

                class 実働時間{
                {field} int
                {static} 実働時間 create(タイムカード, 休憩時間リスト)
                {static} int calcTotalBreakMinutes(タイムカード, 休憩時間リスト)
                }
                休憩時間リスト <.up. 実働時間

                拘束時間 <.up. 実働時間
            }

            package 残業時間{
                class 残業時間{
                {field} int
                {static} 残業時間 create(実働時間, 定時間)
                }

                class 定時間{
                {field} Duration
                +{method} int getMinutes()
                }

                定時間 <.up. 残業時間
            }

            class 労働時間{
             {field} 実働時間
             {field} 残業時間
            }

            労働時間 -down-> 実働時間
            労働時間 -down-> 残業時間
        }

        package 登録時刻{
            class 登録時刻{
            {field} LocalDateTime
            {method}String toString(DateTimeFormatter)
            }
        }
    }

    package サマリ{
        class 月間サマリ{
         -{field} 総実働時間
         -{field} 総残業時間
         {static} 月間サマリ create(List<勤怠レコード>)
        int getTotalActualWorkingMinsValue()
        int getTotalOvertimeValue()
        }

        package 対象年月{
            class 対象年月 {
            {field} String
            -{method}void valid(対象年月)
            }
        }

        package 総実働時間{
            class 総実働時間{
            {field} int
            {static} 総実働時間 create(List<勤怠レコード>)
            }
            月間サマリ -down-> 総実働時間
        }

        package 総残業時間{
            class 総残業時間{
            {field} int
            {static} 総残業時間 create(List<勤怠レコード>)
            }
            月間サマリ -down-> 総残業時間
        }
    }

    top to bottom direction
    勤怠レコード -[hidden]- サマリ
    サマリ -[hidden]- リポジトリ
}

package データソース.CSV{

    class Csvリポジトリ{
       + {method}void write(勤怠レコード)
       + {method}List<勤怠レコード> read(対象年月)
    }

    勤怠リポジトリ --|> Csvリポジトリ
}


@enduml
