@startuml


package API{

    class 勤怠{
     {method} main(String args[])
    }


    package コントローラ{
        class 入力コントローラ{
             + {method} execute(String[])
        }
        class 集計コントローラ{
             + {method} execute(String[])
        }

        top to bottom direction
        入力コントローラ -[hidden]-集計コントローラ
    }


    class バリデータ{
     + {method} isValidArgs(String[])
     - {method} isValidMethodType(String)
    }

}

package サービス{

    class 入力サービス{
     + {method}void persist(対象日付, 開始時刻, 終了時刻, レポジトリ)
     - {method}登録時刻 getRegisteredTime()
    }

    class 月間集計サービス{
     + {method}月間サマリ getMonthlySummary(対象年月、レポジトリ)
    }

    top to bottom direction
    入力サービス -[hidden]-月間集計サービス
}


package ドメイン{

    package リポジトリ{
        interface 勤怠リポジトリ{
           void write(勤怠情報)
           List<勤怠情報> read(対象年月)
        }
    }

    package 勤怠情報{

        class 勤怠情報{
          {field} 対象日付
          {field} 開始時刻
          {field} 終了時刻
          {field} 実働時間
          {field} 残業時間
          {field} 登録時刻
        }

        勤怠情報 -down-> 対象日付
        勤怠情報 -down-> 開始時刻
        勤怠情報 -down-> 終了時刻
        勤怠情報 -down-> 残業時間
        勤怠情報 -down-> 登録時刻

        package 対象日付{
            class 対象日付 {
            - {method}void valid(対象日付)
            }
        }

        package 開始時刻{
            class 開始時刻 {
             {field} 開始時間
             {field} 開始分
             -{method}void valid(開始時刻)
            }
            class 開始時間{
            }
            class 開始分{
            }
            開始時刻 --> 開始時間
            開始時刻 --> 開始分
        }

        package 終了時刻{
            class 終了時刻 {
             {field} 終了時間
             {field} 終了分
             -{method}void valid(終了時刻)
            }
            class 終了時間{
            }
            class 終了分{
            }
            終了時刻 --> 終了時間
            終了時刻 --> 終了分
        }

        package 稼働と実働時間{
            class 稼働時間{
            {static} 稼働時間 create(開始時刻, 終了時刻)
            }
            class 実働時間{
            {static} 実働時間 create(稼働時間, 終了時間)
            }

            稼働時間 <.. 実働時間

            勤怠情報 -down-> 実働時間
        }

        package 残業時間{
            class 残業時間{
            {static} 残業時間 of(実働時間)
            }
        }

        package 登録時刻{
            class 登録時刻{
            {static} 登録時刻 create()
            }
        }
    }

    package サマリ{

        class 月間サマリ{
         -{field} 総実働時間
         -{field} 総残業時間
         {static} 月間サマリ create(List<勤怠情報>)
        }

        package 対象年月{
            class 対象年月 {
            -{method}void valid(対象年月)
            }
        }

        package 総実働時間{
            class 総実働時間{
            {static} 総実働時間 of(List<勤怠情報>)
            }
            月間サマリ -down-> 総実働時間
        }

        package 総残業時間{
            class 総残業時間{
            {static} 総残業時間 calc(List<勤怠情報>)
            }
            月間サマリ -down-> 総残業時間
        }
    }

    top to bottom direction
    勤怠情報 -[hidden]- サマリ
    サマリ -[hidden]- リポジトリ
}

package データソース.CSV{

    class Csvリポジトリ{
       + {method}void write(勤怠情報)
       + {method}List<勤怠情報> read(対象年月)
    }

    勤怠リポジトリ --|> Csvリポジトリ
}


@enduml
