@startuml kintaiDomain
package ドメインモデル{
    package 就業日勤務実績p{
        class 勤務実績{
            勤務日
            開始時刻
            終了時刻
            残業時間
            勤務時間
            勤務実績集計(勤務記録,就業規則):勤務実績
        }
        class 残業{
            残業時間
            残業時間計算(勤務時間):残業時間
        }
        class 勤務時間{
            勤務時間
            勤務時間計算(開始時刻,終了時刻,休憩時間):勤務時間
        }

    }
    package 勤務入力p{
        class 勤務記録{
            勤務日
            開始時刻
            終了時刻
        }
        class 勤務日{
         }
        class 業務開始時刻{
         }
        class 業務終了時刻{
        }
    }
    package 就業規則p{
        class 就業規則{
            始業時刻
            終業時刻
            休憩時刻

            休憩時間計算(開始時刻,終了時刻):休憩時間
        }

        class 休憩{
            休憩開始時刻
            休憩終了時刻
        }

    }


    package 月間累計勤務時間p {
        class 月間累計勤務時間{
            月累計勤務時間
            月累計残業時間
            月累計勤務残業計算(List<勤務実績>):月累計勤務時間、月累計残業時間
        }
        class 月累計勤務{
        }
        class 月累計残業{
        }
    }
    勤務実績 "1" *-- "1" 勤務時間
    勤務実績 "1" *-- "1" 残業
    勤務実績 "1" *-- "1" 就業規則
    勤務実績 "1" *-- "1" 勤務記録

    就業規則 "1" *-- "0...n" 休憩
    
    勤務記録 "1" *-- "1" 勤務日
    勤務記録 "1" *-- "1" 業務開始時刻
    勤務記録 "1" *-- "1" 業務終了時刻

    月間累計勤務時間 "1" *-- "0...n"勤務実績
    月間累計勤務時間 "1" *-- "1" 月累計勤務
    月間累計勤務時間 "1" *-- "1" 月累計残業
}
package サービス層{
    class 勤務記録入力サービス{

    }
    interface 就業日合計記録リポジトリ{

    }
    class 月合計勤務時間サービス{
    }

    勤務記録入力サービス ..> 勤務実績
    勤務記録入力サービス ..> 就業日合計記録リポジトリ
    勤務記録入力サービス ..> 勤務記録
    勤務記録入力サービス ..> 就業規則
    就業日合計記録リポジトリ ..> 勤務実績
    月合計勤務時間サービス ..> 就業日合計記録リポジトリ
    月合計勤務時間サービス ..> 月間累計勤務時間
    月合計勤務時間サービス ..> 勤務実績

}
@enduml