@startuml

title 勤怠管理　ドメイン設計


package 勤怠{

    enum WorkState as "勤務状態" << Enum >>{
     通常
     遅刻
     早退
     欠勤
     忌引
     予定休
     有給
    }

    class WorkTime as "勤務時間"  << Entity >> {
     - int 日付
     - int 時間
     – int 分
     - int 残業分
     - 勤務状態 状態
    }

    class TimeKeeper as "タイムキーパー" << Entity >>{
     - 配列　休憩開始時間
     - 配列　休憩終了時間
     - int 日付
     - int 始業時間
     - int 終業時間
     - WorkTime 勤務時間
    --
     - 勤務時間 calcWorkTime(始業時間, 終業時間)
     + TimeKeeper(日付,始業時間,終業時間)
    }

    TimeKeeper o-- WorkTime

    class MonthlyWorkTimeCard as "月勤務タイムカード"{
     - List<勤務時間>　勤務時間リスト
     - int 年月
     --
     + int 総勤務時間(分)を取得する
     + int 総残業時間(分)を取得する
    }


    interface WorkTimeRepository as "勤務時間リポジトリ"{
      + void input(勤務時間)
      + MonthlyWorkTimeCard　total(int yearMonth)
    }

    WorkTimeRepository -- MonthlyWorkTimeCard

}
@enduml

