@startuml

title 勤怠管理　ドメイン設計


package 勤怠{

    enum 勤務状態 as "WorkState" {
     通常
     遅刻
     早退
     欠勤
     忌引
     予定休
     有給
    }

    class 勤務時間 as "WorkTime"{
     - int 時間
     – int 分
     - int 残業時間
     - int 残業分
     - int 残業総分
     - 勤務状態 状態
    }

    class 勤務時間算出者 as "WorkTimeCalculator"{
    　- 配列　休憩開始時間
    　- 配列　休憩終了時間
    --
     + 勤務時間 calcWorkTime(就業時間, 終業時間)
    }


    class 月勤務時間 as "MonthlyWorkTime"{
     - List<勤務時間>　勤務時間リスト
     - int 年月
     --
     +
    }


    interface 勤務時間リポジトリ as "WorkTimeRepository"{
      + void input(勤務時間)
      + 月勤務時間　total(int yearMonth)
    }

    勤務時間リポジトリ -- 月勤務時間
    勤務時間リポジトリ -- 勤務時間

    class 月勤務時間集計 {
    }
    class 月勤務時間集計者 {
    }
    class TimeKeeper {
    }
}
@enduml

