@startuml

title 勤怠管理　ドメイン設計


package 勤怠{

    enum WorkState as "勤務状態" << Enum >>{
     通常
     遅刻
     早退
     欠勤
     忌引
     予定休
     有給
    }

    class WorkTime as "勤務時間"  << Entity >> {
     - int 日付
     – int 勤務時間分
     - int 残業時間分
     - StartWorkTime 始業時間
     - EndWorkTime 終業時間
     - 勤務状態 状態
    }

    class MonthlyWorkTimeCard as "月勤務タイムカード" << Entity >>{
     - List<勤務時間>　勤務時間リスト
     - WorkDate 年月
     --
     + int 総勤務時間(分)を取得する
     + int 総残業時間(分)を取得する
    }

    MonthlyWorkTimeCard *-- WorkTime


    interface WorkTimeRepository as "勤務時間リポジトリ"{
      + void input(勤務時間)
      + MonthlyWorkTimeCard　findTimeCard(int yearMonth)
    }

    WorkTimeRepository -- MonthlyWorkTimeCard

    class StartWorkTime as "始業時間" << value object >>{
     - int StartTime
    }
    WorkTime --> StartWorkTime

    class EndWorkTime as "終業時間" << value object >>{
     - int EndTime
    }
    WorkTime --> EndWorkTime

    class WorkDate as "勤務日" << value object >>{
     - int date
     - int yearMonth
    }
    WorkTime --> WorkDate
    MonthlyWorkTimeCard --> WorkDate

    class WorkingRule as "就業規則" << Singleton >>{
     - 配列　休憩開始時間
     - 配列　休憩終了時間
    --
     + 勤務時間 calcWorkTime(WorkDate,StartWorkTime,EndWorkTime)
    }
    WorkingRule -- WorkTime

}
@enduml

