@startuml 勤怠管理クラス図
package domain {
    class Attendance<<(E,gray) Entity>> {
        Date date
        AttendanceTime attendanceTime
        WorkDuration workDuration
        OverWorkDuration overWorkDuration
        Instant createdAt
    }

    class AttendanceTime<<(E,gray) Entity>> {
            LocalDateTime start
            LocalDateTime end
    }

    class WorkDuration<<(V,gray) ValueObject>> {
        - final int regularStartTime
        - final int regularEndTime
        - final int lunchBreakStartTime
        - final int lunchBreakEndTime
        - final int nightBreakStartTime
        - final int nightBreakEndTime
        - final int midNightBreakStartTime
        - final int midNightBreakEndTime
        Duration duration
        - Duration calculateDuration(AttendanceTime attendanceTime)
     }

     class OverWorkDuration<<(V,gray) ValueObject>> {
             - final int regularFullTimeDuration
             Duration duration
             - Duration calculateDuration(WorkDuration workDuration)
     }

     class AttendanceRepository<<(R,Cyan) Repository>> {
           + void persist(Attendance attendance)
           + List<Attendance> select(int yearMonth)
      }
}

package datasource {
    class AttendanceRepositoryCsv<<(R,red) RepositoryImpl>> {
        + void persist(Attendance attendance)
        + List<Attendance> select(int yearMonth)
    }
    class AttendanceMapperCsv<<(M,green) Mapper>> {
        void persist(Attendance attendance)
        List<Attendance> select(int yearMonth)
    }
}

package service {
    class AttendanceService<<(S,strategy) Service>> {
       + void input(AttendancePersistRequest request)
       + AttendanceTotalResponse total(int yearMonth)
    }

    class AttendancePersistRequest<<(R,gray) Response>> {
            WorkDuration totalWorkMinutes
            OverWorkDuration totalOverWorkMinutes
    }


    class AttendanceTotalResponse<<(R,gray) Response>> {
        WorkDuration totalWorkMinutes
        OverWorkDuration totalOverWorkMinutes
    }
}

package api {
    class AttendanceApi<<(A,yellow) Api>> {
        void input(String date,String start,String end,String workDuration, String overWorkDuration
                           String createdAt)
        Attendance total(String yerMonth)
    }

}

class main {
}

main --> AttendanceApi
AttendanceApi --> AttendanceService
AttendanceService --> Attendance
AttendanceRepositoryCsv -left-|> AttendanceRepository
AttendanceService --> AttendanceRepository
Attendance --> AttendanceTime
Attendance --> WorkDuration
Attendance --> OverWorkDuration
AttendanceRepositoryCsv --> AttendanceMapperCsv


@enduml
