@startuml 勤怠管理クラス図
package domain {
    class Attendance<<(E,gray) Entity>> {
        Date date
        LocalDateTime start
        LocalDateTime end
        WorkDuration workDuration
        OverWorkDuration overWorkDuration
        Instant createdAt
    }

    class WorkDuration<<(V,gray) ValueObject>> {
        Duration duration
        - Duration calculateDuration(LocalDatetime start, LocalDateTime end)
     }

     class OverWorkDuration<<(V,gray) ValueObject>> {
             Duration duration
             - Duration calculateDuration(WorkDuration workDuration)
     }

     class AttendanceRepository<<(R,Cyan) Repository>> {
           + void persist(Attendance attendance)
           + List<Attendance> select(int yearMonth)
      }

     class AttendanceConst<<Const>> {
        {static} final int regularStartTime
        {static} final int regularEndTime
        {static} final int lunchBreakStartTime
        {static} final int lunchBreakEndTime
        {static} final int nightBreakStartTime
        {static} final int nightBreakEndTime
        {static} final int midNightBreakStartTime
        {static} final int midNightBreakEndTime
        {static} final int regularFullTimeDuration
     }
}

package datasource {
    class AttendanceRepositoryCsv<<(R,red) RepositoryImpl>> {
        + void persist(Attendance attendance)
        + List<Attendance> select(int yearMonth)
    }
    class AttendanceMapperCsv<<(M,green) Mapper>> {
        void persist(Attendance attendance)
        List<Attendance> select(int yearMonth)
    }
}

package service {
    class AttendanceService<<(S,strategy) Service>> {
       + void input(AttendancePersistRequest request)
       + AttendanceTotalResponse total(int yearMonth)
    }

    class AttendancePersistRequest<<(R,gray) Response>> {
            WorkDuration totalWorkMinutes
            OverWorkDuration totalOverWorkMinutes
    }


    class AttendanceTotalResponse<<(R,gray) Response>> {
        WorkDuration totalWorkMinutes
        OverWorkDuration totalOverWorkMinutes
    }
}

package api {
    class AttendanceApi<<(A,yellow) Api>> {
        void input(String date,String start,String end,String workDuration, String overWorkDuration
                           String createdAt)
        Attendance total(String yerMonth)
    }

}

class main {
}

main --> AttendanceApi
AttendanceApi --> AttendanceService
AttendanceService --> Attendance
AttendanceRepositoryCsv -left-|> AttendanceRepository
AttendanceService --> AttendanceRepository
Attendance --> WorkDuration
Attendance --> OverWorkDuration
AttendanceRepositoryCsv --> AttendanceMapperCsv
WorkDuration --> AttendanceConst
OverWorkDuration --> AttendanceConst


@enduml
