@startuml kintai
skinparam PackageStyle rectangle
title ドメインモデル


package サービス層 {
  package 勤務実績 as サービス_勤務実績 {
    interface 勤務実績リポジトリ {
      登録(勤務実績)
    }
  }
  package 勤務実績登録 {
    class 勤務実績登録サービス {
      登録(勤務時刻入力)
    }
  }

  package 就業規則 as サービス{
    interface 就業規則リポジトリ {
      参照():就業規則
    }
  }

  package 月間累計勤務時間参照 {
    class 月間累計勤務時間参照サービス {
      参照(年月):月間累計勤務時間
    }

    interface 月間勤務実績リポジトリ {
      参照(年月): 月間勤務実績
    }
  }
}

package ドメイン層 {
  package 勤怠情報 {

    class 勤務時刻 {
      始業時刻
      終業時刻
    }

    class 勤務実績 {
      勤務日
      勤務時刻
      実働時間
      残業時間
      作成日時
      + create(勤務時刻入力, 就業規則): 勤務実績
    }

    class 実働時間 {
      + create(勤務時間, 就業規則):実働時間
    }

    class 残業時間 {
      + create(実働時間, 規定勤務時刻):残業時間
    }
  }

  package 就業規則 {
    class 就業規則 {
      規定勤務時刻
      休憩時刻リスト
    }

    class 規定勤務時刻 {
      規定始業時刻
      規定終業時刻
    }

    class 休憩時刻 {
      開始時刻
      終了時刻
    }

  }

  package 勤務時刻入力 {
    class 勤務時刻入力 {
      勤務日
      勤務時刻
    }
  }

  ' package 累計勤務時間{

  '   class 累計勤務時間 {
  '     累計実働時間
  '     累計残業時間
  '     + create(勤務実績リスト):累計勤務時間
  '   }

  '   class 累計実働時間 {}
  '   class 累計残業時間 {}
  ' }

  package 月間累計勤務時間{
    class 月間累計勤務時間 {
      累計実働時間
      累計残業時間
      + create (月間勤務実績):月間累計勤務時間
    }

    class 月間勤務実績 {
      勤務実績リスト
    }
  }

}


勤務実績登録サービス ..> 勤務時刻入力
勤務実績登録サービス --> 勤務実績リポジトリ
勤務実績リポジトリ ..> 勤務実績

勤務実績登録サービス --> 就業規則リポジトリ
就業規則リポジトリ ..> 就業規則

勤務実績 "1" *--> "1" 実働時間
勤務実績 "1" *--> "1" 残業時間
勤務実績 "1" *--> "1" 勤務時刻 

月間累計勤務時間参照サービス ..> 月間累計勤務時間 
月間勤務実績リポジトリ ..> 月間勤務実績 
月間累計勤務時間参照サービス --> 月間勤務実績リポジトリ
' 累計勤務時間 "1" *--> "1" 累計実働時間
' 累計勤務時間 "1" *--> "1" 累計残業時間

' 月間累計勤務時間 "1" *--> "1" 累計勤務時間 
月間勤務実績 "1" *--r> "0..*" 勤務実績

就業規則 "1" *--> "0..*" 休憩時刻
就業規則 "1" *--> "1" 規定勤務時刻 

実働時間 ..l> 就業規則
残業時間 ..> 実働時間 
残業時間 ..> 規定勤務時刻

@enduml
