@startuml kintai
skinparam PackageStyle rectangle
title ドメインモデル

package サービス層 {
  package 登録 {
    class 勤務情報登録サービス {
      登録(勤務情報入力)
    }


    interface 勤務情報リポジトリ {
      登録(勤務情報)
    }
  }

  package 参照 {
    class 月間累計時間参照 {
      参照(年月):月間累計時間
    }
  }
}

package ドメイン層 {
  package 勤怠登録 {

    class 勤務時間 {
      始業時刻
      終業時刻
    }

    class 実働時間 {
      + create(勤務時間, 就業規則):実働時間
    }

    class 残業時間 {
      + create(実働時間, 規定勤務時間):残業時間
    }

    ' class 勤務情報 {
    '   日付
    '   実働時間
    '   残業時間
    ' }
    ' https://github.com/biglobe-isp/themis/issues/1#issuecomment-1439452223

    class 勤務情報 {
      勤務日
      勤務時間
      実働時間
      残業時間
      作成日時
    }

    class 勤務情報 {
      + create(勤務情報入力, 就業規則): 勤務情報
    }

    class 勤務情報入力 {
      勤務日
      勤務時間
    }

    ' class 勤務情報ファクトリー {
    '   + create(勤務日，始業時刻，終業時刻): 勤務情報
    ' }
    ' オブジェクト生成に、引数以外で必要な情報があるか？
    ' オブジェクトの生成は、引数だけで完結するか？
    '   外部由来の情報は変更可能性があるか？ 


    ' class 休憩時間 {
    '   算出(休憩時刻リスト):休憩時間
    ' }

  }

  package 就業規則 {
    class 就業規則 {
      規定始業時刻
      規定終業時刻
      休憩時刻リスト
    }

    class 規定勤務時間 {
      規定勤務時間
    }

    class 休憩時刻 {
      開始時刻
      終了時刻
    }
  }

  package 月間累計勤務時間{

    class 月間累計時間 {
      累計実働時間
      累計残業時間
    }

    class 累計実働時間 {}
    class 累計残業時間 {}
  }
}


勤務情報登録サービス ..> 勤務情報
勤務情報登録サービス ..> 勤務情報入力
勤務情報登録サービス -> 勤務情報リポジトリ
' 勤務情報登録サービス ..> 就業規則
勤務情報リポジトリ ..> 勤務情報

勤務情報 ..> 実働時間
勤務情報 ..> 残業時間

月間累計時間参照 ..> 月間累計時間
月間累計時間参照 ..> 勤務情報 
月間累計時間 *--> 累計実働時間
月間累計時間 *--> 累計残業時間

就業規則 *--> 休憩時刻
就業規則 *--> 規定勤務時間
実働時間 ..> 就業規則
残業時間 ..> 実働時間 
残業時間 ..> 規定勤務時間

' 勤務登録情報 <-- 月間累計時間  登録は勤務時間算出と残業時間
' 就業規則が必要  実働時間と残業時間を算出する
' サービス層もかく、参照と登録わける
' 何を永続化するか
@enduml
