@startuml

package domain {
    package 打刻 {
        class AttendanceRecord {
            - AttendanceDate attendanceDate
            - AttendanceTimeInterval attendanceTimeInterval
            - ActualMinutes actualMinutes
            + LocalDate getAttendanceLocalDate()
            + LocalTime getAttendanceStartLocalTime()
            + LocalDate getAttendanceEndLocalTime()
            + int getActualWorkingTimeMinutesLength()
            + int getActualOvertimeMinutesLength()
        }

        class AttendanceRecords {
            - List<AttendanceRecord> records
        }

        package 出勤情報 {
            class AttendanceDate {
                - ZonedDateTime date
            }
            class AttendanceTimeInterval {
                - TimeInterval timeInterval
                + TimeLength intersect(RegulatedBreakTimeInterval regulatedBreakTimeInterval)
                + TimeLength between(TimeUnits unit)
            } 
            class AttendanceTimeMinutes {
                - TimeLength length
                + AttendanceTimeMinutes(AttendanceTimeInterval attendanceTimeInterval)
                + TimeLength excludeBreakTime(\n    AttendanceTimeInterval attendanceTimeInterval, \n    RegulatedBreakTimeShift regulatedBreakTimeShift)
            }
            class AttendanceTimeIntervalFactory {
                + AttendanceTimeInterval create(AttendanceDate attendanceDate, TimeInterval interval)
            }       
        }

        package 実績時間 {
            package 残業時間　{
                class ActualOvertimeMinutes {
                    - TimeLength length
                    + ActualOvertimeMinutes(\n    ActualWorkingTimeMinutes actualWorkingTimeMinutes, \n    RegulatedWorkingTimeMinutes regulatedWorkingTimeMinutes)
                    + int intValue()
                    - boolean hasOvertime()

                }
            }
            package 労働時間 {
                class ActualWorkingTimeMinutes {
                    - TimeLength length
                    + int intValue()
                }
            }
            class ActualMinutes {
                - ActualWorkingTimeMinutes actualWorkingTimeMinutes
                - ActualOvertimeMinutes actualOvertimeMinutes
                + int convertActualWorkingTimeMinutesToHour()
                + int convertActualOvertimeMinutesToHour()
                + int extractRemainderActualWorkingTimeMinutes()
                + int extractRemainderActualOvertimeMinutes()
            }
            class ActualTimeService {
                + ActualMinutes calculateActualMinutes(\n    AttendanceTimeInterval attendanceTimeInterval, \n    RegulatedBreakTimeShift regulatedBreakTimeShift, \n    RegulatedWorkingTimeMinutes regulatedWorkingTimeMinutes)
            }
        }

        package 就業規則 {
            class RegulatedWorkingTimeMinutes {
                - TimeLength length
            }
            class RegulatedWorkingTimeInterval {
                - TimeInterval timeInterval
                + boolean hasFollowedRegulatedStartTime(StartTime startTime)
            }
            class RegulatedBreakTimeInterval {
                - TimeInterval timeInterval
                + TimeLength between(TimeUnits unit)
            }
            class RegulatedBreakTimeShift {
                - List<RegulatedBreakTimeInterval> breakTimeInterval
            }
        }
        class ZonedTimePoint {
            - ZonedDateTime time
            + boolean isEqual(ZonedTimePoint comparison) 
            + boolean isBefore(ZonedTimePoint comparison) 
            + boolean isAfter(ZonedTimePoint comparison) 
            + boolean isEqualOrBefore(ZonedTimePoint comparison) 
            + boolean isEqualOrAfter(ZonedTimePoint comparison) 
        }
        class StartTime {
            - ZonedTimePoint timePoint
        }
        class EndTime {
            - ZonedTimePoint timePoint
        }

        class TimeLength {
            - long length
            - TimeUnits unit
            + TimeLength add(TimeLength addition)
            + TimeLength subtract(TimeLength subtraction)
            + boolean isLonger(TimeLength comparison)
            + TimeLength minuteToHour()
            + TimeLength extractRemainderMinutes()
            - boolean isSameUnit(TimeLength comparison)
        }

        class TimeInterval {
            - StartTime
            - EndTime
            +  TimeIntervalComparedStatus getComparedStatus(TimeInterval comparison)
            + TimeLength between(TimeInterval interval, TimeUnits unit)
            + {static} TimeLength between(StartTime startTime, EndTime endTime)
            - boolean contains(ZonedTimePoint timePoint)
            - boolean containsAll(TimeInterval interval)
            - boolean within(TimeInterval interval)
        }
        
        enum TimeUnits {
            MINUTES
            HOURS
        }
        enum TimeIntervalComparedStatus {
            WITHIN
            CONTAIN
            EQUAL_OR_BEFORE
            EQUAL_OR_AFTER
            OUT_OF
        }

        AttendanceRecords o--> AttendanceRecord
        AttendanceRecord --> AttendanceDate
        AttendanceRecord --> AttendanceTimeInterval
        AttendanceRecord --> ActualMinutes

        ActualMinutes *--> ActualOvertimeMinutes
        ActualMinutes *--> ActualWorkingTimeMinutes

        ActualOvertimeMinutes *--> TimeLength
        ActualOvertimeMinutes -down-> ActualWorkingTimeMinutes
        ActualOvertimeMinutes --> RegulatedWorkingTimeMinutes

        ActualWorkingTimeMinutes *--> TimeLength
        ActualTimeService -up-> ActualOvertimeMinutes
        ActualTimeService -up-> ActualWorkingTimeMinutes
        ActualTimeService -left-> AttendanceTimeInterval
        ActualTimeService -left-> AttendanceTimeMinutes
        ActualTimeService --> RegulatedBreakTimeShift
        ActualTimeService --> RegulatedWorkingTimeMinutes

        AttendanceTimeMinutes *--> TimeLength
        AttendanceTimeMinutes -up-> AttendanceTimeInterval
        AttendanceTimeMinutes --> RegulatedBreakTimeShift
        AttendanceTimeInterval *--> TimeInterval
        AttendanceTimeIntervalFactory -up-> AttendanceDate
        AttendanceTimeIntervalFactory -up-> AttendanceTimeInterval
        AttendanceTimeIntervalFactory --> RegulatedWorkingTimeInterval
        AttendanceTimeIntervalFactory --> TimeInterval

        RegulatedWorkingTimeInterval *--> TimeInterval
        RegulatedBreakTimeInterval *--> TimeInterval
        RegulatedBreakTimeShift o--> RegulatedBreakTimeInterval

        TimeInterval *--> StartTime
        TimeInterval *--> EndTime

        StartTime *--> ZonedTimePoint
        EndTime *--> ZonedTimePoint

        TimeLength *--> TimeUnits

        TimeInterval --> ZonedTimePoint
        TimeInterval --> TimeIntervalComparedStatus
        TimeInterval --> TimeLength
        TimeInterval --> TimeUnits
    }

    ' package 月次集計 {
    '     class AttendanceAggregationMonthly {
    '         - TimeLength totalWorkingTimeMinutesLength
    '         - TimeLength totalOvertimeMinutesLength
    '         + public AttendanceAggregationMonthly(Optional<Integer> totalWorkingTimeMinutes, Optional<Integer> totalOvertimeMinutes)
    '         + int convertActualWorkingTimeMinutesToHour()
    '         + int convertActualOvertimeMinutesToHour()
    '         + int extractRemainderActualWorkingTimeMinutes()
    '         + int extractRemainderActualOvertimeMinutes()
    '     }
    '     class AggregationMonth {
    '         - YearMonth yearMonth
    '         + boolean equalsYearMonth(LocalDate date)
    '         - boolean equalsYear(LocalDate date)
    '         - boolean equalsMonth(LocalDate date)
    '     }
    ' }
}

' package controller {
'     class AttendanceController {
'         - AttendanceRecordingService attendanceRecordService
'         - AttendanceAggregationService attendanceAggregationService
'         + void record(String[] inputParams)
'         + void aggregateMonthly(String[] inputParams)
'　　　　　- void outputAttendanceRecord(AttendanceRecord attendanceRecord) 
'　　　　　- void outputAggregationMonthly(AggregationMonth aggregationMonth, AttendanceAggregationMonthly attendanceAggregationMonthly) 
'     }
'     AttendanceController *--> AttendanceRecordingService
'     AttendanceController *--> AttendanceAggregationService
' }

' package service {
'     class AttendanceRecordingService {
'         - AttendanceRepository attendanceRepository
'         - RegulationRepository regulationRepository
'         + AttendanceRecord register(AttendanceDate attendanceDate, AttendanceTimeInterval attendanceTimeInterval)
'     }
'     class AttendanceAggregationService {
'         - AttendanceRepository attendanceRepository
'         + AttendanceAggregationMonthly aggregateMonthly(AggregationMonth aggregationMonth)
'     }
'     interface AttendanceRepository {
'         + void register(AttendanceRecord attendanceRecord)
'         + AttendanceAggregationMonthly fetchMonthly(AggregationMonth aggregationMonth)
'     }
'     interface RegulationRepository {
'         + fetchBreakTimeIntervalShift(AttendanceDate attendanceDate)
'         + RegulatedWorkingTimeMinutes fetchRegulatedWorkingTimeMinutes(AttendanceDate attendanceDate)
'     }
'     AttendanceRecordingService   *--> AttendanceRepository
'     AttendanceRecordingService   *--> RegulationRepository
'     AttendanceAggregationService *--> AttendanceRepository
' }

' package datasource {
'     class AttendanceRepositoryCsv {
'         + void register(AttendanceRecord attendanceRecord)
'         + AttendanceAggregationMonthly fetchMonthly(AggregationMonth aggregationMonth)
'     }
'     class RegulationRepositoryCsv {
'         + BreakTimeIntervalShift fetchBreakTimeList(AttendanceDate attendanceDate)
'         + RegulatedWorkingTimeMinutes fetchRegulatedWorkingTimeMinutes(AttendanceDate attendanceDate)
'     }
'     class AttendanceCsvDao {
'         - CsvDao<AttendanceRecordEntity> csvDao 
'         - AppCsvProperties appCsvProperties 
'         + void register(AttendanceRecord attendanceRecord)
'         + AttendanceRecordEntities fetchAll(AttendanceDate attendanceDate)
'         + AttendaceRecordEntities fetchMonthly(AggregationMonth aggregationMonth)
'     }
'     class RegulatedBreakTimeCsvDao {
'         - CsvDao<RegulatedBreakTimeEntity> csvDao 
'         - AppCsvProperties appCsvProperties 
'         + RegulatedBreakTimeEntities fetchAll(AttendanceDate attendanceDate)
'     }
'     class RegulatedWorkingTimeMinutesCsvDao {
'         - CsvDao<RegulatedWorkingTimeMinutesEntity> csvDao
'         - AppCsvProperties appCsvProperties 
'         + void write(Writer writer, T bean)
'         + RegulatedWorkingTimeMinutesEntity fetch(AttendanceDate attendanceDate)
'     }
'     class CsvDao<T> {
'         + void writeAll(Writer writer, List<T> beans)
'         + void write(Writer writer, T bean)
'         + List<T> read(Reader reader, Class<? extends T> type)
'     }
'     class AttendanceRecordEntities {
'         - List<AttendanceRecordEntity> records
'         + void upsert(AttendanceRecord record)   
'         + void add(AttendanceRecord record)   
'         + void update(AttendanceRecord record)   
'         + Optional<Integer> indexOf(AttendanceRecord record)        
'     }
'     class AttendanceRecordEntity {
'         - LocalDate ymd
'         - LocalTime startDate
'         - LocalTime endDate
'         - int workingTimeMinutes
'         - int overtimeMinutes
'         - ZonedDateTime updatedAt
'     }
'     class RegulatedBreakTimeEntities {
'         - List<RegulatedBreakTimeEntity> records    
'     }
'     class RegulatedBreakTimeEntity {
'         - LocalDate validStartDate
'         - LocalDate validEndDate
'         - String breakTimeStart
'         - String breakTimeEnd
'     }
'     class RegulatedWorkingTimeMinutesEntity {
'         - LocalDate validStartDate
'         - LocalDate validEndDate
'         - int regulatedWorkingTimeMinutes
'     }
'     AttendanceRepositoryCsv .up.|> AttendanceRepository
'     AttendanceRepositoryCsv --> AttendanceCsvDao
'     AttendanceRecordEntities o--> AttendanceRecordEntity
'     AttendanceCsvDao --> AttendanceRecordEntities
'     AttendanceCsvDao --> AttendanceRecordEntity
'     AttendanceCsvDao *--> CsvDao

'     RegulationRepositoryCsv .up.|> RegulationRepository
'     RegulationRepositoryCsv --> RegulatedBreakTimeCsvDao
'     RegulationRepositoryCsv --> RegulatedWorkingTimeMinutesCsvDao

'     RegulatedBreakTimeCsvDao --> RegulatedBreakTimeEntities
'     RegulatedBreakTimeCsvDao --> RegulatedBreakTimeEntity
'     RegulatedBreakTimeCsvDao *--> CsvDao
'     RegulatedBreakTimeEntities o--> RegulatedBreakTimeEntity

'     RegulatedWorkingTimeMinutesCsvDao --> RegulatedWorkingTimeMinutesEntity
'     RegulatedWorkingTimeMinutesCsvDao *--> CsvDao
' }

@enduml