@startuml
package "api" {
    class Main{
        main()
    }
}

package "service" {
    class sample2
}

package "datasource"{

} 
package "domain"{

} 

'便宜的なデフォルトクラス
package "default"{
    class Main_old
}

sample1--sample2

@enduml