@startuml
package "api" {
    class Main{
        main()
    }
}

package "service" {
    class KintaiService{
        input()
        total()
    }
}

package "datasource"{
    class IKintai{
        getDate()
        getStart()
        getEnd()
        getWorkMinutes()
        getOverWorkMinute()

    }
class CsvWriter{
    writeCsv()
}
class CsvReader{
    getColumn()
}
} 
package "com.naosim.dddwork.domain"{
class KintaiData{
    calcurateJiturodo()
    calcurateZangyo()
}
class KintaiRepository{
    save()
    findKintaiDataByMonth()
}
class MontlyTotalworkTime{
    getWorkTimeHour()
    getWorkTimeMinute()
    getOverWorkTimeHour()
    getOverWorkTimeMinute()

}
class WorkTime{
    getHour()
    getMinute()
    toString()
}
class WorkTimeDuration{
    getHour()
    getMinutes()
}
class WorkDate{
    toString()
}
class Rest
class RestTimeService{
    calcurateRestTime()
}
} 


Main-->KintaiService
Main-->MontlyTotalworkTime
KintaiService-->KintaiData
KintaiService-->KintaiRepository
KintaiService-->MontlyTotalworkTime
KintaiData-->WorkTime
KintaiData-->WorkDate
KintaiData-->WorkTimeDuration
KintaiData--|>IKintai
KintaiData-->RestTimeService
RestTimeService-->Rest

KintaiRepository-->CsvReader
KintaiRepository-->CsvWriter
KintaiRepository-->KintaiData
MontlyTotalworkTime-->WorkTimeDuration
MontlyTotalworkTime-->KintaiData


CsvWriter-->IKintai
@enduml