@startuml
package "api" {
    class Main{
        main()
    }
}

package "service" {
    class inputKintai{
        input()
    }
}

package "datasource"{
    class IKintai{

    }
class CSVwriter{
    writeCSV()
}
} 
package "com.naosim.dddwork.domain"{
class kintaiCalcurater{
    calcurateJiturodo()
    calcurateZangyo()
}
} 


Main-->inputKintai
inputKintai-->kintaiCalcurater
inputKintai-->CSVwriter
kintaiCalcurater-|>IKintai
CSVwriter-->IKintai
@enduml