@startuml
title 勤怠

package api {
    class 勤怠API {
        メイン(入力パラメータ):void
    }
}

package datasource {
    class CSVリポジトリ {
        抽出年月で探す(抽出年月):月次勤怠記録
        保存する(日次勤怠記録):void
    }
}

package service {
    class 勤怠入力サービス {
        勤怠を入力する(日次勤怠記録):void
    }
    class 勤怠集計サービス {
        トータル実働時間を計算する(抽出年月):トータル実働時間
        トータル残業時間を計算する(抽出年月):トータル残業時間
    }
}

package domain {
    interface 勤怠リポジトリ {
        抽出年月で探す(抽出年月):月次勤怠記録
        保存する(日次勤怠記録):void
    }
    interface 時間 {
        時間を取得する():int
        遅い時間か判定する(時間):boolean
    }
    class 抽出年月
    class 日次勤怠記録 {
        勤務日を取得する():勤務日
        開始時刻を取得する():開始時刻
        終了時刻を取得する():終了時刻
        勤怠入力時刻を取得する():勤怠入力時刻
        実働時間を取得する():実働時間
        残業時間を取得する():残業時間
    }
    class 月次勤怠記録 {
        追加する(日次勤怠記録):void
        トータル実働時間を計算する():トータル実働時間
        トータル残業時間を計算する():トータル残業時間
    }
    class 勤務日
    class トータル実働時間
    class トータル残業時間
    class 開始時刻 {
        時間を取得する():int
        遅い時間か判定する(時間):boolean
    }
    class 終了時刻 {
        時間を取得する():int
        遅い時間か判定する(時間):boolean
    }
    class 標準労働時間 {
        時間を取得する():int
    }
    class 休憩時間 {
        開始時刻を取得する():開始時刻
        終了時刻を取得する():終了時刻
    }
    class 労働規則 {
        休憩時間一覧を取得する():List<休憩時間>
        標準労働時間を取得する():標準労働時間
    }
    class 時間帯 {
        オーバーラップする時間帯を取得する(時間帯):Optional<時間帯>
        時間を取得する():int
    }
    class 勤務時間 {
        実働時間を計算する():実働時間
        残業時間を計算する():残業時間
    }
    class 実働時間 {
        時間を取得する():int
    }
    class 残業時間 {
        時間を取得する():int
    }
    class 勤怠入力時刻 {
        時刻を取得する():String
    }
}

' api層からservice層への関連
勤怠API --> 勤務日
勤怠API --> 開始時刻
勤怠API --> 終了時刻
勤怠API --> 勤怠入力時刻
勤怠API --> 日次勤怠記録
勤怠API --> 勤怠入力サービス
勤怠API --> 勤怠集計サービス

' api層からdatasource層への関連
勤怠API --> CSVリポジトリ

' datasource層からdomain層への関連
CSVリポジトリ ..|> 勤怠リポジトリ

' service層からdomain層への関連
勤怠入力サービス --> 勤怠リポジトリ
勤怠入力サービス --> 日次勤怠記録
勤怠集計サービス --> 勤怠リポジトリ
勤怠集計サービス --> 抽出年月

' domain層内の関連
勤怠リポジトリ --> 抽出年月
勤怠リポジトリ --> 日次勤怠記録
勤怠リポジトリ --> 月次勤怠記録
日次勤怠記録 --> 勤務日
日次勤怠記録 --> 開始時刻
日次勤怠記録 --> 終了時刻
日次勤怠記録 --> 勤怠入力時刻
開始時刻 ..|> 時間
終了時刻 ..|> 時間
労働規則 --> 休憩時間
労働規則 --> 標準労働時間
勤務時間 --> 労働規則
月次勤怠記録 --> 日次勤怠記録
月次勤怠記録 --> 勤務日
月次勤怠記録 --> トータル実働時間
月次勤怠記録 --> トータル残業時間
勤務時間 --> 時間帯
日次勤怠記録 --> 勤務時間
時間帯 --> 開始時刻
時間帯 --> 終了時刻
勤務時間 --> 実働時間
勤務時間 --> 残業時間
@enduml