@startuml

package Domain層 {
    package 勤怠パッケージ <<Rectangle>> {

        interface 勤怠リポジトリ

        class 勤怠 <<(C,green)集約ルート>> {
            - 勤務日
            - 出勤時刻
            - 退勤時刻
            - 勤務時間
            - 残業時間
            - 入力時刻
        }

        class 勤務日
        class 出勤時刻
        class 退勤時刻
        class 勤務時間
        class 残業時間
        class 入力時刻

        class 在社時間
        class 休憩時間
        class 休憩開始時刻
        class 休憩終了時刻

        class 月度

        class 勤怠集計サービス
        class 集計結果 {
            - 集計勤務時間
            - 集計残業時間
        }
    }

    package 就業規則パッケージ <<Rectangle>> {

        interface 就業規則リポジトリ

        class 就業規則<<(C,green)集約ルート>> {
            - 勤務時間規則
            - 休憩時間規則
            - 施行日
        }
        class 施行日
        class 勤務時間規則
        class 規定勤務時間
        class 始業時刻
        class 終業時刻
        class 休憩時間規則
        class 規定休憩時間
        class 規定休憩開始時刻
        class 規定休憩終了時刻
    }

    就業規則パッケージ ..> 勤怠パッケージ : 依存方向

    勤怠 o-- 勤務日
    勤怠 o-- 出勤時刻
    勤怠 o-- 退勤時刻
    勤怠 o-- 勤務時間
    勤怠 o-- 入力時刻
    勤怠 o-- 残業時間

    休憩時間 o-- 休憩開始時刻
    休憩時間 o-- 休憩終了時刻

    勤怠集計サービス ..> 勤怠リポジトリ: <<use>>

    就業規則 o-- 施行日
    就業規則 o-- 休憩時間規則
    就業規則 o-- 勤務時間規則

    勤務時間規則 o-- 規定勤務時間

    規定勤務時間 o-- 始業時刻
    規定勤務時間 o-- 終業時刻

    休憩時間規則 "1" o-- "*" 規定休憩時間

    規定休憩時間 o-- 規定休憩開始時刻
    規定休憩時間 o-- 規定休憩終了時刻

    note top of 勤怠
    ・勤務日で一意
    endnote

    note top of 勤怠集計サービス
    ・集計結果を作成する。
    endnote

    note top of 就業規則
    ・施行日で一意
    ・勤務時間(=在社時間 - 休憩時間)を作成する。
    ・残業時間(=勤務時間 - 通常勤務時間)を作成する。
    endnote
}

@enduml