@startuml

package Attendance {

interface AttendanceRepository {
    + 勤怠を永続化する[void input(Attendance)]
    + 勤怠履歴を取得する[AttendanceHistory find()]
}

class "勤怠[Attendance]" as Attendance {
    出勤日[WorkDate]
    就業時間[DutyTime]
    労働時間[WorkMinutes]
    残業時間[OverWorkMinutes]
    + {static} 作成する[Attendance create(WorkDate, StartTime, EndTime)]
    - {static} 労働時間を計算する int calcWorkTime(DutyTime, <color:red>RestTimeRule</color>)
    - {static} 就業時間を計算する int calcDutyTime(DutyTime)
    - {static} 休憩時間合計を計算する int calcTotalRestTime(DutyTime, <color:red>RestTimeRule</color>)
    - {static} 休憩時間を計算する int calcRestTime(DutyTime, RestTime)
    - {static} 時刻を比較しより早い時刻 LocalTime earlyTime(LocalTime, LocalTime)
    - {static} 時刻を比較しより遅い時刻 LocalTime lateTime(LocalTime, LocalTime)
    - {static} 残業時間を計算する int calcOverWorkMinutes(WorkMinutes)
    - {static} <color:red>休憩時間規則を作成する[RestTimeRule makeRestTimeRule(WorkDate)]</color>
    - {static} <color:red>2018/11/14までの休憩時間規則を作成する[RestTimeRule makeRestTimeRuleUntil20181114()]</color>
    - {static} <color:red>2018/11/15以降の休憩時間規則を作成する[RestTimeRule makeRestTimeRule20181115Later()]</color>
}

class "勤怠履歴[AttendanceHistory]" as AttendanceHistory {
    勤怠リスト[AttendanceList]
    + 労働時間を集計する[TotalWorkMinutesByMonth totalWorkMinutesByMonth(TotalYearMonth)]
    + 残業時間を集計する[TotalOverWorkMinutesByMonth totalOverWorkMinutesByMonth(TotalYearMonth)]
}

class "月別労働時間[TotalWorkMinutesByMonth]" as TotalWorkMinutesByMonth {
    月別労働時間[int]
}

class "月別残業時間[TotalOverWorkMinutesByMonth]" as TotalOverWorkMinutesByMonth {
    月別残業時間[int]
}

class "集計年月[TotalYearMonth]" as TotalYearMonth {
    集計年月[YearMonth]
}

class "勤怠リスト[AttendanceList]" as AttendanceList {
    勤怠リスト[List<Attendance>]
}

class "出勤日[WorkDate]" as WorkDate {
    出勤日[LocalDate]
}

class "出勤時刻[StartTime]" as StartTime {
    出勤時刻[LocalTime]
}

class "退勤時刻[EndTime]" as EndTime {
    退勤時刻[LocalTime]
}

class "就業時間[DutyTime] " as DutyTime {
    開始時刻[LocalTime]
    終了時刻[LocalTime]
    + 就業時間の範囲内に休憩時間を含む[boolean withinRange(RestTime)]
}

class "休憩時間[RestTime]" as RestTime {
    開始時刻[LocalTime]
    終了時刻[LocalTime]
}

class "労働時間[WorkMinutes]" as WorkMinutes {
    労働時間[int]
    + 働き過ぎ[boolean isOverWork()]
}

class "残業時間[OverWorkMinutes]" as OverWorkMinutes {
    残業時間[int]
}

class "<color:red>休憩時間規則[RestTimeRule]</color>" as RestTimeRule {
    <color:red>休憩時間規則[List<RestTime>]</color>
}

class "休憩時間規則ファクトリ[RestTimeRuleFactory]" as RestTimeRuleFactory {
    休憩時間リスト[List<RestTime>]
    + 作成する[RestTimeRuleFactory()]
    + 追加する[RestTimeRuleFactory add(LocalTime, LocalTime)]
    + 構築する[<color:red>RestTimeRule</color> build()]
}

AttendanceRepository -down-> Attendance
AttendanceRepository -down-> AttendanceHistory

AttendanceHistory -down-> AttendanceList
AttendanceList -down-> Attendance

AttendanceHistory -down-> TotalWorkMinutesByMonth
AttendanceHistory -down-> TotalOverWorkMinutesByMonth
AttendanceHistory -down-> TotalYearMonth

Attendance -down-> WorkDate
Attendance -down-> StartTime
Attendance -down-> EndTime

Attendance -down-> DutyTime
Attendance -down-> RestTime
Attendance -down-> WorkMinutes
Attendance -down-> OverWorkMinutes
Attendance -down-> RestTimeRule

DutyTime -down-> RestTime

RestTimeRuleFactory -up-> RestTimeRule
RestTimeRuleFactory -up-> RestTime
RestTimeRule -up-> RestTime

}

@enduml
