@startuml

package Attendance {

interface AttendanceRepository {
    +void input(Attendance) //勤怠の永続化
    +AttendanceList find() //勤怠リストの取得
}

class "勤怠[Attendance]" as Attendance {
    出勤日[WorkDate]
    出勤時刻[StartTime]
    退勤時刻[EndTime]
    労働時間[WorkMinutes]
    残業時間[OverWorkMinutes]
    + 作成する[Attendance create(WorkDate, StartTime, EndTime)]
}

class "勤怠履歴[AttendanceHistory]" as AttendanceHistory {
    勤怠リスト[AttendanceList]
    + 労働時間を集計する[TotalWorkMinutesByMonth totalWorkMinutesByMonth(TotalYearMonth)]
    + 残業時間を集計する[TotalOverWorkMinutesByMonth totalOverWorkMinutesByMonth(TotalYearMonth)]
    + 労働時間と残業時間を出力する[void print(TotalWorkMinutesByMonth, TotalOverWorkMinutesByMonth)]
}

class "勤怠リスト[AttendanceList]" as AttendanceList {
    勤怠リスト[List<Attendance>]
}

class "労働時間[WorkMinutes]" as WorkMinutes {
    + 作成する[void WorkMinutes(StartTime, EndTime)]
    + 労働時間を算出する[int calcWorkMinutes(StartTimeHours, StartTimeMinutes, EndTimeHours, EndTimeMinutes)]
}

class "残業時間[OverWorkMinutes]" as OverWorkMinutes {
    + 作成する[void OverWorkMinutes(WorkMinutes)]
    + 残業時間を算出する[int calcOverWorkMinutes(WorkMinutes)]
}

AttendanceRepository -down-> Attendance
AttendanceRepository -down-> AttendanceHistory
AttendanceHistory -down-> AttendanceList
AttendanceList -down-> Attendance
Attendance -down-> WorkMinutes
Attendance -down-> OverWorkMinutes

}

@enduml
