
@startuml

package TotalWorkingHours {

interface TotalWorkingHoursRepository {
    + TotalMonthlyWorkingHours TotalWorkingHours(WorkingMonth) // 集計
}

class "月勤務時間集計[TotalMonthlyWorkingHours]" as TotalMonthlyWorkingHours {
    勤務月[WorkingMonth]
    勤務時間[WorkingHours]
    残業時間[OvertimeHours]
}

TotalWorkingHoursRepository -down-> TotalMonthlyWorkingHours

}

@enduml
