@startuml

package WorkTimeRegistration {

interface WorkTimeRegistrationRepository {
    + void registered(RegisteredWorkingHours) //永続化
}

class "登録済勤務時間[RegisteredWorkingHours]" as RegisteredWorkingHours {
    勤務日[WorkDay]
    始業時間[StartingHours]
    終業時間[ClosingTime]
}

WorkTimeRegistrationRepository -down-> RegisteredWorkingHours
}

@enduml
