@startuml

package java.time {
    class LocalDate
    class LocalTime
    class LocalDateTime
    class Duration
}

package domain {
    package vo {
        class 年
        class 月
        class 日
        class 時
        class 分
        class 秒

        class 日付 {
          - value: LocalDateTime
          {static} of(年, 月, 日): 日付
        }
        日付 *--> LocalDate

        class 時刻 {
          - value: LocalTime
          {static} 時刻 of(時, 分)
          {static} 時刻 of(時, 分, 秒)
        }
        時刻 *--> LocalTime

        class 時間 {
          - value: Duration
          {static} 時間 of(時刻, 時刻)
        }
        時間 *--> Duration

        class 日時 {
          - value: LocalDateTime
          {static} of(年, 月, 日, 時, 分, 秒): 日時
          {static} of(日付, 時刻): 日時
        }
        日時 *--> LocalDateTime

        class 出勤日 {
          {static} of(年, 月, 日): 出勤日
          {static} of(日付): 出勤日
        }
        出勤日 --|> 日付

        class 出勤時刻
        出勤時刻 --|> 時刻

        class 退勤時刻
        退勤時刻 --|> 時刻

        class 実労時間
        実労時間 --|> 時間

        class 残業時間
        残業時間 --|> 時間

        class 休憩時間
        休憩時間 --|> 時間

        class 打刻日時 {
          {static} of(年, 月, 日, 時, 分, 秒): 打刻日時
          {static} of(日付, 時刻): 打刻日時
          {static} of(日時): 打刻日時
        }
        打刻日時 --|> 日時
    }

    class 勤務時間 {
      - 実労時間: 実労時間
      - 休憩時間: 休憩時間
      - 残業時間: 残業時間
    }
    勤務時間 --|> 時間
    勤務時間 o--> 実労時間
    勤務時間 o--> 休憩時間
    勤務時間 o--> 残業時間

    class 勤務規程 {
      ----
      + 算定(出勤時刻, 退勤時刻): 勤務時間
    }
    勤務規程 --> 勤務時間
    勤務規程 ..> 出勤時刻
    勤務規程 ..> 退勤時刻

    class 勤怠記録 {
      - 出勤日: 出勤日
      - 勤務時間: 勤務時間
      - 打刻日時: 打刻日時
    }
    勤怠記録 *--> 出勤日
    勤怠記録 *--> 勤務時間
    勤怠記録 *--> 打刻日時

    interface 勤怠リポジトリ <<Repository>> {
      ----
      + save(勤怠記録)
    }
    勤怠リポジトリ ..> 勤怠記録
}

package service {
    ' Puncher
    class 勤怠管理 <<Service>> {
      - リポジトリ: 勤怠リポジトリ
      ----
      + 打刻(出勤時刻, 退勤時刻)
      + 集計(年, 月): 勤務時間
    }
    勤怠管理 *--> 勤怠リポジトリ
    勤怠管理 ..> 勤務規程
    勤怠管理 --> 勤務時間
}

package repository.file {
    class ファイルデータストア {
    }

    class 勤怠ファイルリポジトリ <<Repository>> {
      - データストア: データストア
      ----
    }
    勤怠ファイルリポジトリ ..|> 勤怠リポジトリ
    勤怠ファイルリポジトリ *-> ファイルデータストア
}

package presentation {
  class コマンド {
    ----
    {static} main(パラメタ)

    入力(パラメタ)
    集計(パラメタ)
  }

  コマンド ..> 勤怠管理
}

@enduml