@startuml

package com.naosim.dddwork.domain.worktotal {
    note top of WorkTimeAggregateTargetYearAndMonth : 集計したい勤怠合計時間の\n年月指定クラス
    class WorkTimeAggregateTargetYearAndMonth {
        - targetYearAndMonth : targetYearAndMonth
        + getValueObject() : targetYearAndMonth
    }

    class TargetYearAndMonth {
        - value : String
        + getValue() : String
    }

    note bottom of WorkMinutesPerYMDNormal : 通常時間集計\n元データクラス
    class WorkMinutesPerYMDNormal {
        - workMinutesPerYMD : WorkMinutesPerYMD
        - workMinutesPerYMDNormalValue : WorkMinutesPerYMDNormalValue
    }

    note bottom of WorkMinutesPerYMDNormalValue : 通常時間集計結果\n元データクラス
    class WorkMinutesPerYMDNormalValue {
        - value : Integer
    }

    note bottom of WorkMinutesPerYMDOver : 残業時間集計\n元データクラス
    class WorkMinutesPerYMDOver {
        - workMinutesPerYMD : WorkMinutesPerYMD
        - WorkMinutesPerYMDOverValue : WorkMinutesPerYMDOverValue
    }

    note bottom of WorkMinutesPerYMDOverValue : 残業時間集計結果\n元データクラス
    class WorkMinutesPerYMDOverValue {
        - value : Integer
    }

    note bottom of WorkMinutesPerYMD : 合計時間集計\n年月日クラス
    class WorkMinutesPerYMD {
        - calucutateTargetYearAndMonth : String
    }

    note right of WorkTimeAggregateDatas : 勤怠合計時間集計\n元データクラス
    class WorkTimeAggregateDatas {
        - workMinutesPerYMDNormal : WorkMinutesPerYMDNormal
        - workMinutesPerYMDOver : WorkMinutesPerYMDOver
    }

    note bottom of TotalWorkNormalTimeYearAndMonth : 通常勤務時間合計クラス
    class TotalWorkNormalTimeYearAndMonth {
        - value : Integer
        + getValue() : Integer
    }

    note bottom of TotalWorkOverTimeYearAndMonth : 残業勤務時間合計クラス
    class TotalWorkOverTimeYearAndMonth {
        - value : Integer
        + getValue() : Integer
    }

    note top of WorkTimeTotalRepository : 勤怠合計時間集計\nインターフェイス
    interface WorkTimeTotalRepository {
        + totalWorkTimeCalucurate(workTimeAggregateTargetYearAndMonth:\nWorkTimeAggregateTargetYearAndMonth) : WorkTimeAggregateDatas
    }
}

package com.naosim.dddwork.datasource {
    note top of WorkTimeTotalRepositoryFile : 勤怠合計時間集計\n実装クラス
    class WorkTimeTotalRepositoryFile {
        + totalWorkTimeCalucurate(workTimeAggregateTargetYearAndMonth:\nWorkTimeAggregateTargetYearAndMonth) : WorkTimeAggregateDatas
    }
}

WorkTimeAggregateTargetYearAndMonth -- TargetYearAndMonth

WorkTimeTotalRepository -- WorkTimeAggregateTargetYearAndMonth
WorkTimeTotalRepository -- WorkTimeAggregateDatas

WorkTimeAggregateDatas "1" o-- "0..*" WorkMinutesPerYMDNormal
WorkTimeAggregateDatas "1" o--"0..*"  WorkMinutesPerYMDOver
WorkTimeAggregateDatas "1" *--"1" TotalWorkNormalTimeYearAndMonth
WorkTimeAggregateDatas "1" *--"1" TotalWorkOverTimeYearAndMonth

WorkMinutesPerYMDNormal "1" *--"1" WorkMinutesPerYMD
WorkMinutesPerYMDNormal "1" *--"1" WorkMinutesPerYMDNormalValue

WorkMinutesPerYMDOver "1" *--"1" WorkMinutesPerYMD
WorkMinutesPerYMDOver "1" *--"1" WorkMinutesPerYMDOverValue

WorkTimeTotalRepository<...WorkTimeTotalRepositoryFile


@enduml