@startuml


class WorkDateAndTime {
    - workDate : WorkDate
    - workStartTime : WorkStartTime
    - workEndTime : WorkEndTime
    - workRecordTime : WorkRecordTime
}

class WorkDate {
    - value : String
    + getValue() : String
}

class WorkStartTime {
    - value : String
    + getValue() : String
}

class WorkEndTime {
    - value : String
    + getValue() : String
}

class WorkRecordTime {
    - value : String
    + getValue() : String
}

interface WorkTimeInputRepository {
    + doWorktimeTaskExecute(workTimeInputParam : WorkDateAndTime):void
}

WorkDateAndTime -- WorkDate
WorkDateAndTime -- WorkStartTime
WorkDateAndTime -- WorkEndTime
WorkDateAndTime -- WorkRecordTime
WorkTimeInputRepository --> WorkDateAndTime

class WorkTimeInputRepositoryFile {
    + doWorktimeTaskExecute(workDateAndTime:WorkDateAndTime) : void
}

WorkTimeInputRepository <|.. WorkTimeInputRepositoryFile
@enduml