@startuml

package com.naosim.dddwork.domain.workdateandtime {

    note left of WorkDateAndTime : 勤怠時間登録\登録情報クラス
    class WorkDateAndTime {
        - workDate : WorkDate
        - workStartTime : WorkStartTime
        - workEndTime : WorkEndTime
        - workRecordTime : WorkRecordTime
    }

    note bottom of WorkDate : 登録年月日クラス
    class WorkDate {
        - value : String
        + getValue() : String
    }

    note bottom of WorkStartTime : 勤務開始時間クラス
    class WorkStartTime {
        - value : String
        + getValue() : String
    }

    note bottom of WorkEndTime : 終業時間クラス
    class WorkEndTime {
        - value : String
        + getValue() : String
    }

    note bottom of WorkRecordTime : 操作時間クラス
    class WorkRecordTime {
        - value : String
        + getValue() : String
    }

    note top of WorkTimeMinutes : 勤務時間計算クラス
    class WorkTimeMinutes {
         - normalWorkTimeMinutes : NormalWorkTimeMinutes
         - overWorkTimeMinutes : OverWorkTimeMinutes
    }

    note bottom of NormalWorkTimeMinutes : 通常勤務時間計算クラス
    class NormalWorkTimeMinutes {
        - value : Integer
        + getValue() : Integer
    }

    note bottom of OverWorkTimeMinutes : 残業時間計算クラス
    class OverWorkTimeMinutes {
        - value : Integer
        + getValue() : Integer
    }

    note top of WorkTimeRegistRepository : 勤怠時間登録\nインターフェイス
    interface WorkTimeRegistRepository {
        + registWorkTime(workTimeInputParam : WorkDateAndTime):void
    }
}

package com.naosim.dddwork.datasource {
    note bottom of WorkTimeRegistRepositoryFile : 勤怠時間登録\n実装クラス
    class WorkTimeRegistRepositoryFile {
        + registWorkTime(workDateAndTime:WorkDateAndTime) : void
    }
}

WorkDateAndTime --> WorkDate
WorkDateAndTime --> WorkStartTime
WorkDateAndTime --> WorkEndTime
WorkDateAndTime --> WorkRecordTime

WorkTimeMinutes "1" *--"1" NormalWorkTimeMinutes
WorkTimeMinutes "1" *--"1" OverWorkTimeMinutes

WorkTimeRegistRepository --> WorkDateAndTime
WorkTimeRegistRepository --> WorkTimeMinutes

WorkTimeRegistRepository <|.. WorkTimeRegistRepositoryFile

WorkTimeRegistRepositoryFile --> WorkTimeMinutes

@enduml