@startuml

package com.naosim.dddwork.domain.worktotal {
    note top of WorkTimeAggregateTargetYearAndMonth : 集計したい勤怠合計時間の\n年月指定クラス
    class WorkTimeAggregateTargetYearAndMonth {
        - targetYearAndMonth : targetYearAndMonth
        + getValueObject() : targetYearAndMonth
    }

    class TargetYearAndMonth {
        - value : String
    }

    note bottom of WorkMinutesPerYMDNormal : 通常時間集計\n元データクラス
    class WorkMinutesPerYMDNormal {
        - workMinutesPerYMD : WorkMinutesPerYMD
        - workMinutesPerYMDNormalValue : WorkMinutesPerYMDNormalValue
    }

    note bottom of WorkMinutesPerYMDNormalValue : 通常時間集計結果\n元データクラス
    class WorkMinutesPerYMDNormalValue {
        - value : Integer
    }

    note bottom of WorkMinutesPerYMDOver : 残業時間集計\n元データクラス
    class WorkMinutesPerYMDOver {
        - workMinutesPerYMD : WorkMinutesPerYMD
        - WorkMinutesPerYMDOverValue : WorkMinutesPerYMDOverValue
    }

    note bottom of WorkMinutesPerYMDOverValue : 残業時間集計結果\n元データクラス
    class WorkMinutesPerYMDOverValue {
        - value : Integer
    }

    note bottom of WorkMinutesPerYMD : 合計時間集計\n年月日クラス
    class WorkMinutesPerYMD {
        - calucutateTargetYearAndMonth : String
    }

    note top of WorkTimeAggregateOrigins : 勤怠合計時間集計\n元データクラス
    class WorkTimeAggregateOrigins {
        - workMinutesPerYMDNormal : WorkMinutesPerYMDNormal
        - workMinutesPerYMDOver : WorkMinutesPerYMDOver
    }

    note top of TotalWorkTimeYearAndMonth : 勤務時間合計クラス
    class TotalWorkTimeYearAndMonth {
        - totalWorkNormalTimeYearAndMonth:TotalWorkNormalTimeYearAndMonth
        - totalWorkOverTimeYearAndMonth:TotalWorkOverTimeYearAndMonth
    }

    note bottom of TotalWorkNormalTimeYearAndMonth : 通常勤務時間合計クラス
    class TotalWorkNormalTimeYearAndMonth {
        - value : Integer
    }

    note bottom of TotalWorkOverTimeYearAndMonth : 残業勤務時間合計クラス
    class TotalWorkOverTimeYearAndMonth {
        - value : Integer
    }

    note top of WorkTimeTotalRepository : 勤怠合計時間集計\nインターフェイス
    interface WorkTimeTotalRepository {
        + totalWorkTimeCalucurate(workTimeAggregateTargetYearAndMonth:\nWorkTimeAggregateTargetYearAndMonth) : WorkTimeAggregateOrigins
    }

}

WorkTimeAggregateTargetYearAndMonth --> TargetYearAndMonth

WorkTimeTotalRepository --> WorkTimeAggregateTargetYearAndMonth

WorkTimeTotalRepository "1" o-- "0..*" WorkTimeAggregateOrigins
WorkTimeAggregateOrigins "1" o-- "0..*" WorkMinutesPerYMDNormal
WorkTimeAggregateOrigins "1" o--"0..*"  WorkMinutesPerYMDOver
WorkMinutesPerYMDOver "1" *--"1" WorkMinutesPerYMD
WorkMinutesPerYMDOver "1" *--"1" WorkMinutesPerYMDOverValue

WorkMinutesPerYMDNormal "1" *--"1" WorkMinutesPerYMD
WorkMinutesPerYMDNormal "1" *--"1" WorkMinutesPerYMDNormalValue

TotalWorkTimeYearAndMonth"1" *--"1" TotalWorkNormalTimeYearAndMonth
TotalWorkTimeYearAndMonth"1" *--"1" TotalWorkOverTimeYearAndMonth

WorkTimeTotalRepository "1" *--"1" TotalWorkTimeYearAndMonth


@enduml