/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kintai;

import kintai.api.AttendanceApi;
import kintai.datasource.AttendanceMapperCsv;
import kintai.datasource.AttendanceMapperCsvImpl;
import kintai.datasource.AttendanceRepositoryCsv;

import kintai.domain.AttendanceRepository;
import kintai.service.AttendanceInputRequest;
import kintai.service.AttendanceService;
import kintai.service.AttendanceTotalResponse;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

import java.nio.file.Path;
import java.nio.file.Paths;

@SpringBootApplication
public class Main {
    @Bean
    public static AttendanceApi attendanceApi() {
        return new AttendanceApi(attendanceService());
    }

    @Bean
    public static AttendanceService attendanceService() {
        return new AttendanceService(attendanceRepository());
    }

    @Bean
    public static AttendanceRepository attendanceRepository() {
        return new AttendanceRepositoryCsv(attendanceMapperCsv(), Paths.get("data.csv"));
    }

    @Bean
    public static AttendanceMapperCsv attendanceMapperCsv() {
        return new AttendanceMapperCsvImpl();
    }

    public static void main(String[] args) {
        SpringApplication.run(Main.class, args);
        if (args.length < 1) {
            throw new RuntimeException("引数が足りません");
        }

        AttendanceApi api = new AttendanceApi(
                attendanceService());

        String methodType = args[0];

        if ("input".equals(methodType)) {
            if (args.length < 4) {
                throw new RuntimeException("引数が足りません");
            }
            api.input(new AttendanceInputRequest(args[1],args[2],args[3]));
        } else if ("total".equals(methodType)) {
            if (args.length < 2) {
                throw new RuntimeException("引数が足りません");
            }
            AttendanceTotalResponse totalResponse = api.total(args[1]);

            System.out.println("勤務時間: " + totalResponse.getTotalWorkMinutes() / 60 + "時間" + totalResponse.getTotalWorkMinutes() % 60 + "分");
            System.out.println("残業時間: " + totalResponse.getTotalOverWorkMinutes() / 60 + "時間" + totalResponse.getTotalOverWorkMinutes() % 60 + "分");
        }
    }
}
