@startuml 勤怠管理

package datasource {
    class 勤怠リポジトリCSV << datasource >> {
        +void persist(日次勤怠)
        +Option<月次勤怠> findMonthlyAttendance()
    }
}

package domain {
    package rule {
        class 就業規則 {
           
        }

        enum 休憩時間 {
            昼休み
            夕方休憩
            深夜休憩
            +int calcActualTotalBreakTime(勤怠開始時刻,勤怠終了時刻,ChronoUnit)
        }
    }

    package monthly {
        entity 月次勤怠 {
            勤怠年月
            当月の日次勤怠
        }

        class 当月の日次勤怠 {
            List<日次勤怠> value
        }

        class 勤怠年月 {
            YearMonth value        
        }
    }

    package daily {
        entity 日次勤怠 {
            勤怠日付
            勤怠開始時刻
            勤怠終了時刻
            勤務時間
            残業時間
        }
        
        class 勤怠日付 {
            LocalDate value        
        }

        class 勤怠開始時刻 {
            LocalTime value        
        }

        class 勤怠終了時刻 {
            LocalTime value        
        }

        class 勤務時間_分 {
            int value         
        }

        class 残業時間_分 {
            int value
        }
    }
    
    月次勤怠-->勤怠年月
    月次勤怠-->当月の日次勤怠
    当月の日次勤怠  "1" o-- "0..31" 日次勤怠
    日次勤怠-->勤怠日付
    日次勤怠-->勤怠開始時刻
    日次勤怠-->勤怠終了時刻
    日次勤怠-->勤務時間_分
    日次勤怠-->残業時間_分
    勤務時間_分--->休憩時間
}

package service {
    class 勤怠管理サービス << service >> {
        +void inputAttendance(日次勤怠)
        +月次勤怠 totalWorkingHours(勤怠年月)
    }
    class 日次勤怠ファクトリ {
        +日次勤怠 create(勤怠日付,勤怠開始時刻,勤怠終了時刻)
    }
    interface 勤怠リポジトリ << repository >> {
        +void persist(日次勤怠)
        +Option<月次勤怠> findMonthlyAttendance()
    }
    勤怠管理サービス-->日次勤怠ファクトリ
    勤怠管理サービス-->勤怠リポジトリ
    勤怠リポジトリ-->月次勤怠
    勤怠リポジトリ-->日次勤怠
    勤怠リポジトリ<|.. 勤怠リポジトリCSV
}

package api {
    class 勤怠管理メイン {
        +void main(String[] args)
    }
    class 集計結果 {
        勤務時間
        残業時間
    }
    勤怠管理メイン-->勤怠管理サービス
}
@enduml
